version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "postgres_auth"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "54322:5432"
